name: Build sitemap(s) for app(s)

on:
  schedule:
    - cron: '0 0 * * 0' # weekly

  workflow_dispatch:
    inputs:
      apps:
        description: 'Comma-separated list of the names of app(s) to build sitemaps for; default: build a sitemap for each app'
        required: false
        default: ''

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 1
          token: ${{ secrets.GH_ACCESS_TOKEN}}

      - name: Install Python 3.9 and pip
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends software-properties-common
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get install -y --no-install-recommends \
              git \
              python3.9 \
              python3 \
              python3-pip
          python3.9 -m pip install pip
          python3.9 -m pip install setuptools

      - name: Install sitemap build utility
        run: python3.9 -m pip install -r ${GITHUB_WORKSPACE}/tools/build-sitemaps/requirements.txt

      - name: Build sitemap(s)
        run: python3.9 ${GITHUB_WORKSPACE}/tools/build-sitemaps ${{ github.event.inputs.apps }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit Changes
        uses: EndBug/add-and-commit@v7.4.0
        with:
          author_name: Biosimulations-Daemon
          author_email: biosimulationsdaemon@gmail.com
          branch: dev
          message: 'Updated sitemaps [skip ci]'
          signoff: true
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN}} # Leave this line unchanged
