name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - run: |
          git fetch --no-tags --prune --depth=5 origin dev
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - name: Install dependencies
        working-directory: ./biosimulations
        run: npm ci && npm install -g @nrwl/cli

      - name: Lint
        working-directory: ./biosimulations
        run: nx affected:lint --base=origin/dev

      - name: Build
        working-directory: ./biosimulations
        run: nx affected:build --base=origin/dev --prod
      - name: Test
        working-directory: ./biosimulations
        run: nx affected:test --base=origin/dev --code-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          flags: frontEnd
          file: ./biosimulations/coverage/apps/biosimulations-frontend/lcov.info
