name: Format Source Code  
on:
  push:
    branches: [dev]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.5
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN}}

      - name: Install Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: lts/fermium
          cache: npm

          
      - name: Install Nrwl CLI
       
        run: npm install -g @nrwl/cli

            
      - name: Install npm dependencies
       
        run: npm ci
        
      - name: Format files
       
        run: nx format --all
        
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit Changes 
        uses: EndBug/add-and-commit@v7.4.0
        with:
          author_name: Biosimulations-Daemon
          author_email: biosimulationsdaemon@gmail.com
          branch: dev
          message: 'chore: format files. [skip ci]'
          signoff: true
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN}} # Leave this line unchanged       
